---
# configure carbon cache daemon
# create configuration files required for carbon cache
- name: Create carbon cache configuration files
  copy:
    remote_src: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ graphite_run_user }}"
    group: "{{ graphite_run_group }}"
    force: no
  with_items:
    - { src: "{{ graphite_data_dir }}/conf/carbon.conf.example", dest: "{{ graphite_data_dir }}/conf/carbon.conf" }
    - { src: "{{ graphite_data_dir }}/conf/storage-schemas.conf.example", dest: "{{ graphite_data_dir }}/conf/storage-schemas.conf" }

- name: Configure carbon cache daemon
  ini_file:
    path: "{{ graphite_data_dir }}/conf/carbon.conf"
    create: no
    section: cache
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ graphite_carbon_cache_ini }}"
